### ISSUE TITLE
An error when I compile  DRL_graph_exploration

### ISSUE THREAD

**Issue by sumingzs11** [RobustFieldAutonomyLab/DRL_graph_exploration#4]
![image](https://user-images.githubusercontent.com/44395128/119502654-be49fd80-bd9c-11eb-90b2-c0a423f71a09.png)
when I do the final step make, it occurs an error:
![image](https://user-images.githubusercontent.com/44395128/119502922-05d08980-bd9d-11eb-97ae-2dc193b03d1d.png)

I don't know how to solve it

**Comment by fanfeichen** [comment]
It looks like pybind11 has a problem with Point2 Class. Have you installed the newest GTSAM via their official website? If you installed the one from their website, please delete it:

```
sudo rm -r /usr/local/lib/libgtsam* /usr/local/include/gtsam*
```

, and use the link we provided to install GTSAM:

  ```
  git clone -b emex --single-branch https://bitbucket.com/jinkunw/gtsam
  cd gtsam
  mkdir build && cd build
  cmake ..
  sudo make install
  ```

In the newer GTSAM version, there is no Point2 Class so pybind11 has the problem to convert Point2. If you have the correct dependencies, you will see these lines at the beginning to indicate that the configuration is correct:

```
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include;/usr/include;/usr/local/include/gtsam/3rdparty/Eigen/
-- Found pybind11: /usr/local/include (found version "2.6.3" dev1)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/YOUR_NAME/DRL_graph_exploration/build
[  4%] Building CXX object CMakeFiles/planner2d.dir/src/Planner2D.cpp.o
```

**Comment by sumingzs11** [comment]
![2021-07-15 12-28-01 的屏幕截图](https://user-images.githubusercontent.com/44395128/125729045-ccff123e-9f1a-4204-98f5-c6678dea5ae1.png)
First of all, thank you for your reply. I will try your method
But what puzzles me most is that it's not the first time that I report an error in the ss2d.cpp file. Why doesn't point2 report an error in the first place
